[project]
name = "polars-warp"
version = "0.1.5"
description = "Add your description"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.1",
    "polars>=1.38.1",
    "pyarrow>=23.0.1",
    "xlsxwriter>=3.2.9",
]
