[project]
name = "polars-warp"
version = "0.1.5"
description = "Add your description"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "polars>=1.21.0",
    "pyarrow>=19.0.0",
    "xlsxwriter>=3.2.9",
]
